-- Nonaktifkan pemeriksaan foreign key sementara
SET FOREIGN_KEY_CHECKS = 0;

-- DROP TABLE dalam urutan yang aman (anak ke parent)
DROP TABLE IF EXISTS articles;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS msmes;
DROP TABLE IF EXISTS cultures;
DROP TABLE IF EXISTS tour_packages;
DROP TABLE IF EXISTS destinations;
DROP TABLE IF EXISTS users;

-- Aktifkan kembali pemeriksaan foreign key
SET FOREIGN_KEY_CHECKS = 1;

-- USERS TABLE
CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- DESTINATIONS
CREATE TABLE destinations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  short_description VARCHAR(255) NOT NULL,
  description TEXT NULL,
  category VARCHAR(255) NOT NULL,
  image VARCHAR(255) NULL,
  latitude  DECIMAL(10, 8) NULL,
  longitude DECIMAL(11, 8) NULL,
  gallery TEXT NULL, -- JSON array
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- TOUR PACKAGES
CREATE TABLE tour_packages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT NULL,
  price FLOAT NULL,
  duration VARCHAR(255)  NULL,
  min_persons INT,
  max_persons INT,
  whatsapp_contact VARCHAR(20) NULL,
  whatsapp_booking_url VARCHAR(500) NULL,
  facilities TEXT NULL, -- JSON array
  image VARCHAR(255) NULL,
  popular BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- CULTURES
CREATE TABLE cultures (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  description TEXT NULL,
  image VARCHAR(255) NULL,
  category VARCHAR(255),
  gallery TEXT NULL, -- JSON array
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- MSMES
CREATE TABLE msmes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  brand VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  phone VARCHAR(20) NULL,
  instagram VARCHAR(255) NULL,
  shopee VARCHAR(255) NULL,
  whatsapp VARCHAR(20) NULL,
  user_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- PRODUCTS
CREATE TABLE products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  price DECIMAL(15, 2) NOT NULL,
  image VARCHAR(255) NULL,
  description TEXT NOT NULL,
  material VARCHAR(255) NOT NULL,
  durability VARCHAR(255) NOT NULL,
  delivery_time VARCHAR(255) NOT NULL,
  msme_id INT NOT NULL,
  related_products TEXT NULL, -- JSON array
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ARTICLES
<<<<<<< HEAD
=======
DROP TABLE IF EXISTS articles;

>>>>>>> c72853d76138d0ed848dee52f24269cfc1dea801
CREATE TABLE articles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  author_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE NOT NULL,
  content LONGTEXT NOT NULL,
  excerpt TEXT NULL,
  category VARCHAR(255) NOT NULL,
  featured_image VARCHAR(255) NULL,
  status ENUM('draft', 'pending', 'published', 'rejected') DEFAULT 'draft',
  is_featured BOOLEAN DEFAULT FALSE,
  view_count INT DEFAULT 0,
  tags TEXT NULL, -- JSON array
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  published_at TIMESTAMP NULL,
  FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
<<<<<<< HEAD
);
=======
);
>>>>>>> c72853d76138d0ed848dee52f24269cfc1dea801
